services:
  app:
    environment:
      APP_ENV: local
      APP_DEBUG: "true"
    volumes:
      - ./:/var/www
      - /var/www/vendor
      - /var/www/bootstrap/cache

  webserver:
    ports:
      - "8080:80"
